### ISSUE TITLE
README file

### ISSUE THREAD

**Issue by zachdyer** [tonnerre/golang#1]
How come every readme file written with instructions on Golang assumes your working on Linux or Mac and not Windows. `export GOPATH=$HOME/go` which is equivalent to `set GOPATH=%USERPROFILE%\go`. I would have used Linux on this machine if I could get it working on my new machine but the duel boot screen doesn't come up. So I guess I'm stuck with Windows.

**Comment by tonnerre** [comment]
This repository here is obsolete; the official Go Git repository now lives at https://github.com/golang/go. Please report your bug there.
